[package]
name = "fantaporno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
reqwest = "0.11.18"
scraper = "0.17.1"
sea-orm = { version = "0.11.3", features = ["macros", "sqlx-sqlite", "runtime-tokio-rustls"] }
thiserror = "1.0.40"
tokio = { version = "1.29.1", features = ["macros", "rt", "rt-multi-thread", "fs"] }
