CREATE TABLE pornstars (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL);
CREATE TABLE positions (id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, pornstar_id INTEGER NOT NULL, date DATETIME NOT NULL, position INTEGER NOT NULL, UNIQUE (pornstar_id, date));
CREATE TABLE players (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, telegram_id BIGINT NOT NULL, tag VARCHAR(255) DEFAULT NULL, chat_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL, budget INTEGER UNSIGNED NOT NULL, UNIQUE (id, chat_id));
CREATE TABLE teams (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, player_id INTEGER NOT NULL, pornstar_id INTEGER NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME DEFAULT NULL);
CREATE TABLE chats (id BIGINT NOT NULL PRIMARY KEY, start_date DATETIME NOT NULL, lang CHAR(2) NOT NULL DEFAULT "en");
